spring:
  #MySQL数据库
  datasource:
    first:
      url: jdbc:mysql://182.254.221.58:3306/test?useSSL=false&&characterEncoding=utf8
      username: root
      password: Zoulu19900206@
      driver-class-name: com.mysql.jdbc.Driver
      name: testDruid
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计，wall用于防火墙
      filters: stat,wall,log4j
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性打开mergeSql功能；慢sql记录
      connectionProperties: druid.stat.mergeSql=true;druif.stat.slowSqlMillis=5000
      minldle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileldle: true
      testOnBorrow: false
      testOnReturn: false
    second:
      url: jdbc:mysql://182.254.221.58:3306/test2?useSSL=false&&characterEncoding=utf8
      username: root
      password: Zoulu19900206@
      driver-class-name: com.mysql.jdbc.Driver
      name: test2Druid
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计，wall用于防火墙
      filters: stat,wall,log4j
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性打开mergeSql功能；慢sql记录
      connectionProperties: druid.stat.mergeSql=true;druif.stat.slowSqlMillis=5000
      minldle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileldle: true
      testOnBorrow: false
      testOnReturn: false



  #JPA
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  # Redis数据库索引（默认为0）
  redis:
        database: 0
        # Redis服务器地址
        host: 182.254.221.58
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password: zoulu19900206
        # 连接池最大连接数（使用负值表示没有限制）
        pool:
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 0



# 自定义属性
com:
  neo:
    title: 小破天
    description: 你好

# 日志
logging:
  file: logback.log
  level:
    com.favorites: DEBUG
    org:
      springframework.web: INFO
      hibernate: ERROR


